language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
script: coverage run --source wavefile ./setup.py test
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libsndfile1 portaudio19-dev
install:
- pip install --allow-external PyAudio --allow-unverified PyAudio PyAudio
- pip install numpy
- pip install coveralls
after_success:
- coveralls


